MODELS:
  OPENAI:
      MODEL_NAME: gpt-4-turbo-preview
  GEMINI:
      MODEL_NAME: gemini-2.0-flash
  EMBEDDINGMODEL:
      MODEL_NAME: BAAI/bge-base-en-v1.5
VECTOR_DB:
  DBPATH: "./vectordb/singapore"